### ISSUE TITLE
build error: non-zero (13) exit code from bucharestgold/centos7-s2i-nodejs:latest

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/centos7-s2i-nodejs#35]
When using [mean-booster](https://github.com/bucharest-gold/mean-booster) + nodeshift + rhoaster, depending on the configuration of the environment, we see an error.

**locally**  `oc cluster up`  (v3.9.0-alpha) + `nodeshift`

```console
10:31 $ npm run openshift

> mean-booster@1.0.0 openshift /home/hf/Desktop/mean-booster
> nodeshift --strictSSL=false --nodeVersion=8.x --build.forcePull=true

2018-02-19T13:31:43.199Z INFO loading configuration
2018-02-19T13:31:43.209Z INFO using namespace myproject at https://127.0.0.1:8443
2018-02-19T13:31:43.240Z INFO creating archive of package.json, README.md, server.js, app
2018-02-19T13:31:43.303Z INFO using existing build configuration mean-booster-s2i
2018-02-19T13:31:43.308Z INFO using existing image stream mean-booster
2018-02-19T13:31:43.308Z INFO uploading binary archive /home/hf/Desktop/mean-booster/tmp/nodeshift/build/archive.tar
2018-02-19T13:31:47.128Z INFO binary upload complete
2018-02-19T13:31:47.128Z INFO waiting for build to finish
2018-02-19T13:31:50.441Z TRACE ---> Installing application source
2018-02-19T13:31:50.443Z TRACE ---> Building your Node application from source
2018-02-19T13:31:50.443Z TRACE ---> Using 'npm install'
2018-02-19T13:32:56.579Z TRACE error: build error: non-zero (13) exit code from bucharestgold/centos7-s2i-nodejs:latest
2018-02-19T13:32:57.666Z ERROR build failed with message: Assemble script failed.
2018-02-19T13:32:57.667Z ERROR Assemble script failed.
2018-02-19T13:32:57.667Z ERROR Status code undefined
```

**locally**  `oc cluster up`  (v3.9.0-alpha) + `rhoaster`

```console
10:19 $ npm run test:integration

> mean-booster@1.0.0 test:integration /home/hf/Desktop/mean-booster
> tape test/integration/*.js | tap-spec

    No deployment found. Deploying...
    2018-02-19T13:19:32.004Z INFO loading configuration
    2018-02-19T13:19:32.007Z INFO using namespace myproject at https://127.0.0.1:8443
    2018-02-19T13:19:32.011Z INFO creating archive of package.json, README.md, server.js, app
    2018-02-19T13:19:32.052Z INFO creating build configuration mean-booster-s2i
    2018-02-19T13:19:32.052Z INFO Using s2i image bucharestgold/centos7-s2i-nodejs with tag latest
    2018-02-19T13:19:32.144Z INFO creating image stream mean-booster
    2018-02-19T13:19:32.151Z INFO uploading binary archive /home/hf/Desktop/mean-booster/tmp/nodeshift/build/archive.tar
    2018-02-19T13:19:35.840Z INFO binary upload complete
    2018-02-19T13:19:35.840Z INFO waiting for build to finish
    2018-02-19T13:19:59.454Z TRACE ---> Installing application source
    2018-02-19T13:19:59.486Z TRACE ---> Building your Node application from source
    2018-02-19T13:19:59.486Z TRACE ---> Using 'npm install'
    2018-02-19T13:21:01.685Z TRACE error: build error: non-zero (13) exit code from bucharestgold/centos7-s2i-nodejs:latest
2018-02-19T13:21:03.220Z ERROR build failed with message: Assemble script failed.
Error: Assemble script failed.
    at module.exports (/home/hf/Desktop/mean-booster/node_modules/rhoaster/node_modules/nodeshift/lib/binary-build.js:59:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Service unavailable
    at waitForDeployment (/home/hf/Desktop/mean-booster/node_modules/rhoaster/index.js:98:9)
    at <anonymous>
    ..................................................


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mean-booster@1.0.0 test:integration: `tape test/integration/*.js | tap-spec`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mean-booster@1.0.0 test:integration script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hf/.npm/_logs/2018-02-19T13_21_55_082Z-debug.log
```

The same code works on travis --> https://travis-ci.org/bucharest-gold/mean-booster/builds/343428482#L1589

Apparently we can not run the minishift in travis, so it would be interesting to be able to use the `oc cluster up` locally to be as close as possible to the CI.

**Comment by helio-frota** [comment]
My docker dns is not working well.

with firewall enabled:
```
16:19 $ npm run openshift

> mean-booster@1.0.0 openshift /home/hf/Desktop/mean-booster
> nodeshift --strictSSL=false

2018-02-28T19:19:46.128Z INFO loading configuration
2018-02-28T19:19:46.142Z INFO using namespace myproject at https://127.0.0.1:8443
2018-02-28T19:19:46.164Z INFO creating archive of package.json, README.md, server.js, app
2018-02-28T19:19:46.243Z INFO creating build configuration mean-booster-s2i
2018-02-28T19:19:46.244Z INFO Using s2i image bucharestgold/centos7-s2i-nodejs with tag latest
2018-02-28T19:19:46.291Z INFO creating image stream mean-booster
2018-02-28T19:19:46.295Z INFO uploading binary archive /home/hf/Desktop/mean-booster/tmp/nodeshift/build/archive.tar
2018-02-28T19:19:52.073Z INFO binary upload complete
2018-02-28T19:19:52.074Z INFO waiting for build to finish
2018-02-28T19:20:22.969Z TRACE ---> Installing application source
2018-02-28T19:20:23.019Z TRACE ---> Building your Node application from source
2018-02-28T19:20:23.019Z TRACE ---> Installing dependencies
2018-02-28T19:20:23.019Z TRACE ---> Using 'npm install --only=production'
2018-02-28T19:20:23.487Z TRACE npm info it worked if it ends with ok
2018-02-28T19:20:23.487Z TRACE npm info using npm@5.6.0
2018-02-28T19:20:23.487Z TRACE npm info using node@v9.4.0
2018-02-28T19:20:23.706Z TRACE npm info lifecycle mean-booster@1.0.0~preinstall: mean-booster@1.0.0
2018-02-28T19:20:54.118Z TRACE npm ERR! code ENOTFOUND
2018-02-28T19:20:54.119Z TRACE npm ERR! errno ENOTFOUND
2018-02-28T19:20:54.119Z TRACE npm ERR! network request to https://registry.npmjs.org/angular failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
2018-02-28T19:20:54.119Z TRACE npm ERR! network This is a problem related to network connectivity.
2018-02-28T19:20:54.120Z TRACE npm ERR! network In most cases you are behind a proxy or have bad network settings.
2018-02-28T19:20:54.120Z TRACE npm ERR! network
2018-02-28T19:20:54.120Z TRACE npm ERR! network If you are behind a proxy, please make sure that the
2018-02-28T19:20:54.120Z TRACE npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
2018-02-28T19:20:54.164Z TRACE 
2018-02-28T19:20:54.164Z TRACE npm ERR! A complete log of this run can be found in:
2018-02-28T19:20:54.164Z TRACE npm ERR!     /opt/app-root/src/.npm/_logs/2018-02-28T19_20_54_121Z-debug.log
2018-02-28T19:20:54.950Z TRACE error: build error: non-zero (13) exit code from bucharestgold/centos7-s2i-nodejs:latest
2018-02-28T19:20:57.474Z ERROR build failed with message: Assemble script failed.
2018-02-28T19:20:57.475Z ERROR Assemble script failed.
2018-02-28T19:20:57.475Z ERROR Status code undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mean-booster@1.0.0 openshift: `nodeshift --strictSSL=false`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mean-booster@1.0.0 openshift script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hf/.npm/_logs/2018-02-28T19_20_57_484Z-debug.log
```

firewall disabled:

```
17:24 $ npm run openshift

> mean-booster@1.0.0 openshift /home/hf/Desktop/mean-booster
> nodeshift --strictSSL=false

2018-02-28T20:25:08.847Z INFO loading configuration
2018-02-28T20:25:08.858Z INFO using namespace myproject at https://127.0.0.1:8443
2018-02-28T20:25:08.878Z INFO creating archive of package.json, README.md, server.js, app
2018-02-28T20:25:09.012Z INFO using existing build configuration mean-booster-s2i
2018-02-28T20:25:09.017Z INFO using existing image stream mean-booster
2018-02-28T20:25:09.018Z INFO uploading binary archive /home/hf/Desktop/mean-booster/tmp/nodeshift/build/archive.tar
2018-02-28T20:25:13.418Z INFO binary upload complete
2018-02-28T20:25:13.419Z INFO waiting for build to finish
2018-02-28T20:25:26.843Z TRACE ---> Installing application source
2018-02-28T20:25:26.849Z TRACE ---> Building your Node application from source
2018-02-28T20:25:26.849Z TRACE ---> Installing dependencies
2018-02-28T20:25:26.850Z TRACE ---> Using 'npm install --only=production'
2018-02-28T20:25:27.126Z TRACE npm info it worked if it ends with ok
2018-02-28T20:25:27.126Z TRACE npm info using npm@5.6.0
2018-02-28T20:25:27.126Z TRACE npm info using node@v9.4.0
2018-02-28T20:25:27.335Z TRACE npm info lifecycle mean-booster@1.0.0~preinstall: mean-booster@1.0.0
2018-02-28T20:40:51.823Z TRACE npm ERR! code ETIMEDOUT
2018-02-28T20:40:51.824Z TRACE npm ERR! errno ETIMEDOUT
2018-02-28T20:40:51.827Z TRACE npm ERR! network request to https://registry.npmjs.org/express failed, reason: connect ETIMEDOUT 151.101.0.162:443
2018-02-28T20:40:51.827Z TRACE npm ERR! network This is a problem related to network connectivity.
2018-02-28T20:40:51.828Z TRACE npm ERR! network In most cases you are behind a proxy or have bad network settings.
2018-02-28T20:40:51.828Z TRACE npm ERR! network
2018-02-28T20:40:51.828Z TRACE npm ERR! network If you are behind a proxy, please make sure that the
2018-02-28T20:40:51.828Z TRACE npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
2018-02-28T20:40:51.890Z TRACE 
2018-02-28T20:40:51.894Z TRACE npm ERR! A complete log of this run can be found in:
2018-02-28T20:40:51.894Z TRACE npm ERR!     /opt/app-root/src/.npm/_logs/2018-02-28T20_40_51_828Z-debug.log
2018-02-28T20:40:52.724Z TRACE error: build error: non-zero (13) exit code from bucharestgold/centos7-s2i-nodejs:latest
2018-02-28T20:41:05.656Z ERROR build failed with message: Assemble script failed.
2018-02-28T20:41:05.656Z ERROR Assemble script failed.
2018-02-28T20:41:05.657Z ERROR Status code undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mean-booster@1.0.0 openshift: `nodeshift --strictSSL=false`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mean-booster@1.0.0 openshift script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hf/.npm/_logs/2018-02-28T20_41_05_666Z-debug.log
```

not resolves `https://registry.npmjs.org/angular`

```
[hf@T440 ~]$ docker run -it --rm busybox sh -c 'cat /etc/resolv.conf && echo && nslookup https://registry.npmjs.org/angular'
nameserver 8.8.8.8

Server:    8.8.8.8
Address 1: 8.8.8.8

nslookup: can't resolve 'https://registry.npmjs.org/angular'
```

probably can be closed, but would be nice to have a confirmation.

**Comment by helio-frota** [comment]
confirmed on ubuntu 
![screenshot from 2018-02-28 21-27-03](https://user-images.githubusercontent.com/6443576/36820745-3288102e-1cce-11e8-9fa7-0cde0017be63.png)

**Comment by lincolnthree** [comment]
Hey guys,

We're seeing this issue trying to deploy a new Node.js app/CronJob ... it seems sporadic. Is there something we're missing? I don't really see a resolution in this issue or am I missing it?

```
Cloning "https://github.com/snowdrop/github-repo-cleanup-scripts " ...
	Commit:	8b5820a87c6bb2698be891732a6d21dbd752ef49 (Support loading variables from environment)
	Author:	Lincoln Baxter, III <lincoln@redhat.com>
	Date:	Mon May 14 12:01:53 2018 -0400
Pulling image "172.30.1.1:5000/github-cleanup/github-cleanup:latest" ...
---> Installing application source
---> Restoring build artifacts...
npm info it worked if it ends with ok
npm info using npm@5.6.0
npm info using node@v10.1.0
npm ERR! missing script: postinstall
npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/app-root/src/.npm/_logs/2018-05-14T17_37_38_317Z-debug.log
error: build error: non-zero (13) exit code from bucharestgold/centos7-s2i-nodejs@sha256:a1bec22f67b845c142f80ec0dba91986307865b5253cb35914dc2b5a0b8fac9c
```

Any assistance would be super appreciated!

Thanks,
~Lincoln

**Comment by lance** [comment]
Hi @lincolnthree - yours is a legitimate bug that was not covered by this issue. The problem is that when we are restoring build artifacts [here](https://github.com/bucharest-gold/centos7-s2i-nodejs/blob/master/s2i/assemble#L48), we run `npm run postinstall` explicitly. 

A short term fix for this is to just add a noop postinstall script in your package.json.

I've opened an issue for the problem [here](https://github.com/bucharest-gold/centos7-s2i-nodejs/issues/89).

**Comment by lincolnthree** [comment]
Ah gotcha. Thanks, Lance. That makes sense. Will give that a shot!
